// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Models;

namespace api.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api.Models.Grad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("naziv");

                    b.HasKey("ID");

                    b.ToTable("grad");
                });

            modelBuilder.Entity("api.Models.Hrana", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HranilicaID")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tip");

                    b.Property<int>("TrenutnaKolicina")
                        .HasColumnType("int")
                        .HasColumnName("trenutnaKolicina");

                    b.HasKey("ID");

                    b.HasIndex("HranilicaID");

                    b.ToTable("hrana");
                });

            modelBuilder.Entity("api.Models.Hranilica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LokacijaID")
                        .HasColumnType("int");

                    b.Property<int>("MaxKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("maxKapacitet");

                    b.Property<int>("TrenutniKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("trenutniKapacitet");

                    b.HasKey("ID");

                    b.HasIndex("LokacijaID");

                    b.ToTable("hranilica");
                });

            modelBuilder.Entity("api.Models.Lokacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GradID")
                        .HasColumnType("int");

                    b.Property<int>("MaxKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("maxKapacitet");

                    b.Property<string>("NazivLokacije")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazivLokacije");

                    b.Property<int>("TrenutniKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("trenutniKapacitet");

                    b.HasKey("ID");

                    b.HasIndex("GradID");

                    b.ToTable("lokacija");
                });

            modelBuilder.Entity("api.Models.Hrana", b =>
                {
                    b.HasOne("api.Models.Hranilica", "Hranilica")
                        .WithMany("Hrana")
                        .HasForeignKey("HranilicaID");

                    b.Navigation("Hranilica");
                });

            modelBuilder.Entity("api.Models.Hranilica", b =>
                {
                    b.HasOne("api.Models.Lokacija", "Lokacija")
                        .WithMany("Hranilice")
                        .HasForeignKey("LokacijaID");

                    b.Navigation("Lokacija");
                });

            modelBuilder.Entity("api.Models.Lokacija", b =>
                {
                    b.HasOne("api.Models.Grad", "Grad")
                        .WithMany("Lokacije")
                        .HasForeignKey("GradID");

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("api.Models.Grad", b =>
                {
                    b.Navigation("Lokacije");
                });

            modelBuilder.Entity("api.Models.Hranilica", b =>
                {
                    b.Navigation("Hrana");
                });

            modelBuilder.Entity("api.Models.Lokacija", b =>
                {
                    b.Navigation("Hranilice");
                });
#pragma warning restore 612, 618
        }
    }
}
